### ISSUE TITLE
The solution is no longer effective

### ISSUE THREAD

**Issue by lrh450330** [Millionarc/datadome-cookie-generator#1]
Can you give me your contact information, such as email

**Comment by Millionarc** [comment]
Hello, sorry for such a late response. The code I have on here will need updating and depends on the type of DataDome on you're site. My solution is for CH/LE cookie generation. Also, you will need to update some of the values in the POST requests to different one's depending on your site and the current DataDome version. Such as ddv, stcfp, etc.
